apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-config
  namespace: monitoring
data:
  grafana.ini: |
    [log]
    ; # Either "debug", "info", "warn", "error", "critical", default is "info"
    ; # we change from info to debug level
    level = debug
