apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persistentvolume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yashodhan/Documents/Workspace/Cloud-DevOps-Playground/kubernetes-practice/monitoring/grafana/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistentvolumeclaim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-provisioning-persistentvolumeclaim
#   namespace: monitoring
# spec:
# storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Mi
