# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: grafana-pv
#   namespace: monitoring
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 50Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/grafana"
#     type: Directory
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 49Mi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-provisioning-pvc
#   namespace: monitoring
# spec:
# storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Mi
