apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  # type: NodePort
  type: ClusterIP
  selector:
    app: grafana
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http-grafana
      # nodePort: 33000
