namespace: monitoring
helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
resources:
  - namespace.yaml
  - ingress.yaml
  - prometheus/config-map.yaml
  - prometheus/persistent-volume-claim.yaml
  # - prometheus/deployment.yaml
  - prometheus/statefulset.yaml
  - prometheus/service.yaml
  - grafana/config-map.yaml
  - grafana/persistent-volume-claim.yaml
  # - grafana/deployment.yaml
  - grafana/statefulset.yaml
  - grafana/service.yaml
