apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: storage-testing
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yashodhan/Documents/Workspace/Cloud-DevOps-Playground/kubernetes-practice/storage/data"
