# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: prometheus-pv
#   namespace: monitoring
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 50Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data/prometheus"
#     type: Directory
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
