apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistentvolume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yashodhan/Documents/Workspace/Cloud-DevOps-Playground/kubernetes-practice/monitoring/prometheus/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-persistentvolumeclaim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
