helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx

namespace: ingress-testing

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml